services:
  wtsb-web-ui:
    build:
      dockerfile: Dockerfile.BlazorUI
    container_name: wtsb-web-ui
    ports:
      - "5000:80"
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - "wtsb-sql"
    restart: always
  wtsb-web-api:
    build:
      dockerfile: Dockerfile.WebAPI
    container_name: wtsb-web-api
    ports:
      - "5001:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - "wtsb-sql"
    restart: always
  wtsb-sql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: wtsb-sql
    user: root
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - "wtsbdata:/var/opt/mssql/data/"
      - "wtsblog:/var/opt/mssql/log/"
      - "wtsbsecrets:/var/opt/mssql/secrets/"
    restart: always
volumes:
  wtsbdata:
  wtsblog:
  wtsbsecrets: